jobs:
- job: ${{ parameters.name }}
  displayName: Loom tests
  strategy:
    matrix:
      io:
        scope: io::driver
      blocking:
        scope: runtime::tests
      sync:
        scope: sync::tests
      slab:
        scope: util::slab
  pool:
    vmImage: ubuntu-16.04

  steps:
  - template: azure-install-rust.yml
    parameters:
      rust_version: ${{ parameters.rust }}

  - script: cargo test --lib --release --features "full" -- --nocapture $(scope)
    env:
      RUSTFLAGS: '--cfg loom'
      LOOM_MAX_PREEMPTIONS: 2
      CI: 'True'
    displayName: $(scope)
    workingDirectory: $(Build.SourcesDirectory)/tokio
