jobs:
- job: ${{ parameters.name }}
  displayName: Loom tests
  strategy:
    matrix:
      rest:
        scope: --skip loom_pool
      pool_group_a:
        scope: loom_pool::group_a
      pool_group_b:
        scope: loom_pool::group_b
      pool_group_c:
        scope: loom_pool::group_c
      pool_group_d:
        scope: loom_pool::group_d
      pool_group_e:
        scope: loom_pool::group_e
      pool_group_f:
        scope: loom_pool::group_f
  pool:
    vmImage: ubuntu-16.04

  steps:
  - template: azure-install-rust.yml
    parameters:
      rust_version: ${{ parameters.rust }}

  - script: RUSTFLAGS="--cfg loom" cargo test --lib --release --features "full" -- --nocapture $(scope)
    env:
      LOOM_MAX_PREEMPTIONS: 2
      CI: 'True'
    displayName: $(scope)
    workingDirectory: $(Build.SourcesDirectory)/tokio
