jobs:
- job: ${{ parameters.name }}
  displayName: Miri
  pool:
    vmImage: ubuntu-16.04

  steps:
  - template: azure-install-rust.yml
    parameters:
      rust_version: nightly

  - script: |
      rustup component add miri
      cargo miri setup
      rm -rf $(Build.SourcesDirectory)/tokio/tests
    displayName: Install miri

  - script: cargo miri test --features rt-core,rt-threaded,rt-util,sync
    env:
      CI: 'True'
    displayName: cargo miri test
    workingDirectory: $(Build.SourcesDirectory)/tokio
