jobs:
- job: ${{ parameters.name }}
  displayName: Loom tests
  strategy:
    matrix:
      runtime:
        scope:
          - "runtime::tests"
      rest:
        scope:
          - "io::driver"
          - "sync::tests"
          - "util::slab"
  pool:
    vmImage: ubuntu-16.04

  steps:
  - template: azure-install-rust.yml
    parameters:
      rust_version: ${{ parameters.rust }}

  - ${{ each s in scope }}:
    - script: RUSTFLAGS="--cfg loom" cargo test --lib --release --features "full" -- --nocapture $(s)
      env:
        LOOM_MAX_PREEMPTIONS: 2
        CI: 'True'
      displayName: $(s)
      workingDirectory: $(Build.SourcesDirectory)/tokio
